AllCops:
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'public/uploads/attachment/**/*'
    - 'public/uploads/tmp/**/*'
    - 'app/views/**/*'
    - 'bin/**/*'
  RunRailsCops: true
  DisplayCopNames: true

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false
